### ISSUE TITLE
crash when using fluid conduit to push xp into soul binder on skyfactory 2

### ISSUE THREAD

**Issue by bcdaedalus** [CrazyPants/EnderIO#1586]
crash reports as  following   ender io version: EnderIO-1.7.10-2.2.6.317

 --- Minecraft Crash Report ----
// I feel sad now :(

Time: 1/5/15 2:26 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at crazypants.enderio.xp.ExperienceContainer.canFill(ExperienceContainer.java:151)
	at crazypants.enderio.xp.ExperienceContainer.fill(ExperienceContainer.java:161)
	at crazypants.enderio.machine.soul.TileSoulBinder.fill(TileSoulBinder.java:207)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduitNetwork.fillFrom(EnderLiquidConduitNetwork.java:102)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduitNetwork.extractFrom(EnderLiquidConduitNetwork.java:58)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduit.doExtract(EnderLiquidConduit.java:249)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduit.updateEntity(EnderLiquidConduit.java:223)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by tterrag1098** [comment]
This is fixed by https://github.com/CrazyPants/EnderIO/commit/791bcf02714466149ed89e019377336f81ff8de7
