### ISSUE TITLE
Crash on connecting any two energy components

### ISSUE THREAD

**Issue by ipatrol** [CrazyPants/EnderIO#1650]
These crashes occur when any machine that accepts or produces energy is connected to any sort of conduit or cable from either EnderIO or another mod. After crashing, the world cannot be opened again. Log is as follows:
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 1/11/15 11:44 PM
Description: Exception in server tick loop

java.lang.IncompatibleClassChangeError: Class TileMultipart_cmp$$21 does not implement the requested interface cofh.api.energy.IEnergyReceiver
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:291)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:264)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:221)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:32)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:542)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_120_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_20, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1016741384 bytes (969 MB) / 2678587392 bytes (2554 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 103
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 71 mods loaded, 71 mods active
```
And a list of other mods that would, if included, make this page absurdly long.

**Comment by belug23** [comment]
Same problem over here. It was crashing at the startup so we removed any conduits and after connecting one it crashed again.

**Comment by 6210classick** [comment]
are you using the latest version  of COFH and EIO ?

**Comment by belug23** [comment]
It's those two :
ender io 1.7.10-2.2.6.317
cofh Core 1.7.10-3.0.0B9-71

**Comment by ipatrol** [comment]
Updating CoFH Core (along with TF, TE, and MFR) seems to resolve the problem. You really should add version-sensitive dependencies instead of just having it crash on us.

**Comment by belug23** [comment]
You updated to which version? cause we did last friday and it was still crashing?

**Comment by tterrag1098** [comment]
It could be *ANY MOD* with the CoFH API in it and outdated. Please update all mods that might use RF.

**Comment by ipatrol** [comment]
Note however, there's still an occasional crash when breaking Mekanism universal cables next to a capacitor bank.
