### ISSUE TITLE
World Destroying crash with Applied Energistics 2 & IO Cables

### ISSUE THREAD

**Issue by Vardak** [CrazyPants/EnderIO#1672]
Tried to attach a power conduit over a ME cable, world crashes repeatedly.

From the log

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/14/15 3:07 AM
Description: Ticking block entity

java.lang.AbstractMethodError: crazypants.enderio.conduit.me.MEConduitGrid.isWorldAccessable()Z
 at appeng.me.GridNode.FindConnections(GridNode.java:236)
 at appeng.me.GridNode.updateState(GridNode.java:147)
 at crazypants.enderio.conduit.me.MEConduit.updateEntity(MEConduit.java:182)
 at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)
 at net.minecraft.world.World.func_72939_s(World.java:1939)
 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
 at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by tterrag1098** [comment]
rv1 is no longer supported
