### ISSUE TITLE
Ender IO and Magical Crops

### ISSUE THREAD

**Issue by Peacie** [CrazyPants/EnderIO#1688]
There is a problem with Enderio Farms and some Magical Crops. I can´t find out, what seed, but it does not happens with the normal minico seeds.

Some seedsi used to test the crash are fire, fire resistance, night vision, regeneration.

I deleteted the machine with mcedit and i can start my world.

Please excuse my terrible english

**Comment by 6210classick** [comment]
what version of EIO & FORGE & Magical Crops are you using ?

**Comment by Peacie** [comment]
Playing Skyfactroy 2.2.2 

EnderIO-1.7.10-2.2.6.317.jar 
forge-1.7.10-10.13.2.1277-universal.jar

**Comment by Peacie** [comment]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType$2.match(TileFarmStation.java:53)
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType.itemMatches(TileFarmStation.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType.isTool(TileFarmStation.java:67)
	at crazypants.enderio.machine.farm.TileFarmStation.isMachineItemValidForSlot(TileFarmStation.java:297)
	at crazypants.enderio.machine.AbstractMachineEntity.func_94041_b(AbstractMachineEntity.java:164)
	at crazypants.enderio.machine.farm.TileFarmStation.insertResult(TileFarmStation.java:497)
	at crazypants.enderio.machine.farm.TileFarmStation.insertHarvestDrop(TileFarmStation.java:478)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:385)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:305)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:97)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.func_145845_h(AbstractPoweredMachineEntity.java:31)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType$2.match(TileFarmStation.java:53)
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType.itemMatches(TileFarmStation.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation$ToolType.isTool(TileFarmStation.java:67)
	at crazypants.enderio.machine.farm.TileFarmStation.isMachineItemValidForSlot(TileFarmStation.java:297)
	at crazypants.enderio.machine.AbstractMachineEntity.func_94041_b(AbstractMachineEntity.java:164)
	at crazypants.enderio.machine.farm.TileFarmStation.insertResult(TileFarmStation.java:497)
	at crazypants.enderio.machine.farm.TileFarmStation.insertHarvestDrop(TileFarmStation.java:478)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:385)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:305)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:97)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.func_145845_h(AbstractPoweredMachineEntity.java:31)

-- Block entity being ticked --
Details:
	Name: blockFarmStationTileEntity // crazypants.enderio.machine.farm.TileFarmStation
	Block type: ID #727 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-17,72,221), Chunk: (at 15,4,13 in -2,13; contains blocks -32,0,208 to -17,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #727 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: SF2 Try 3
	All players: 1 total; [EntityPlayerMP['Peacie1970'/126539, l='SF2 Try 3', x=-20.40, y=74.00, z=227.67]]
	Chunk stats: ServerChunkCache: 600 Drop: 0
	Level seed: 7058881811987909869
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-68,64,248), Chunk: (at 12,4,8 in -5,15; contains blocks -80,0,240 to -65,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 668412 game time, 668412 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 42781 (now: false), thunder time: 7714 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by 6210classick** [comment]
i just checked their site and the latest version is 3.2.0 Public BETA 15a , hence the BETA there is bound to be problems so it might not be EIO fault did you tried other farms for other mods like MFR ?

**Comment by Peacie** [comment]
MFR cant harvest Magical Crops. 
Its as i say a part of Skyfactory 2, believe, that Magicl Crops delivers no or wrong item id from the harvested crop.
I try to figure out something, what seed it is and if som other ender io options can fix that.
Thank you for now, i will post my trys with that

**Comment by tterrag1098** [comment]
Magical crops is providing an ItemStack with a null item. This should not be possible and if it did not crash here it would crash in 100 other places. Report it to them.
