### ISSUE TITLE
conduit item bug

### ISSUE THREAD

**Issue by parlador** [CrazyPants/EnderIO#1699]
Hello.

I have this crashreport after connect item conduit on ender furnace:

java.lang.NullPointerException: Ticking block entity
	at pl.asie.lib.tile.TileMachine.func_94128_d(TileMachine.java:273)
	at crazypants.enderio.conduit.item.ItemConduit.canConnectToExternal(ItemConduit.java:546)
	at crazypants.enderio.conduit.AbstractConduit.updateConnections(AbstractConduit.java:418)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:393)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

I use last version of mod enderop. asielib, Gany's End

**Comment by 6210classick** [comment]
what EIO & FORGE are you using ? plz provide more details 

isn't ender furnace suppose to sent its output to ender chest only ?

**Comment by parlador** [comment]
I use this version:

enderio: 2.2.6.317
forge: 10.13.2.1286

**Comment by parlador** [comment]
if i remove asielib mode, i have this crash repport:

-- Head --
Stacktrace:
	at pl.asie.lib.tile.TileMachine.func_94128_d(TileMachine.java:273)
	at crazypants.enderio.conduit.item.ItemConduit.canConnectToExternal(ItemConduit.java:546)
	at crazypants.enderio.conduit.AbstractConduit.updateConnections(AbstractConduit.java:418)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:393)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #1144 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (92,54,-30), Chunk: (at 12,3,2 in 5,-2; contains blocks 80,0,-32 to 95,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1144 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by parlador** [comment]
sorry, for last post. Now is crash repport:

java.lang.AbstractMethodError: crazypants.enderio.conduit.me.MEConduitGrid.isWorldAccessable()Z
	at appeng.me.GridNode.FindConnections(GridNode.java:236)
	at appeng.me.GridNode.updateState(GridNode.java:147)
	at crazypants.enderio.conduit.me.MEConduit.updateEntity(MEConduit.java:182)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at appeng.me.GridNode.FindConnections(GridNode.java:236)
	at appeng.me.GridNode.updateState(GridNode.java:147)
	at crazypants.enderio.conduit.me.MEConduit.updateEntity(MEConduit.java:182)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)

**Comment by MatthiasMann** [comment]
As written in the release notes:
AE2 rv1 and older are no longer supported
https://github.com/CrazyPants/EnderIO/blob/master/ReleaseNotes.txt#L20
