### ISSUE TITLE
Ender IO / Thermal Expansion server crash 1.7.10

### ISSUE THREAD

**Issue by DJDaemonix** [CrazyPants/EnderIO#1711]
Hello,

Having recently updated Ender IO & Thermal Expansion, i encounter a server crash on startup.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 18/01/15 11:55
Description: Exception in server tick loop

java.lang.IncompatibleClassChangeError: Class thermalexpansion.block.cell.TileCell does not implement the requested interface cofh.api.energy.IEnergyReceiver
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.conduit.power.NetworkPowerManager.doApplyRecievedPower(NetworkPowerManager.java:152)
	at crazypants.enderio.conduit.power.NetworkPowerManager$InnerTickHandler.tickEnd(NetworkPowerManager.java:539)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_112_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:722)

This server crash leaves us unable to use our modpack. I am willing to provide any information regarding the mod versions and the modpack.

Regards

**Comment by MatthiasMann** [comment]
You have a mods using different versions of the RF API.
