### ISSUE TITLE
Game Crashing bug

### ISSUE THREAD

**Issue by timbob1232** [CrazyPants/EnderIO#1749]
using ender IO (EnderIO-1.7.10-2.2.7.325) and EnviroMine (EnviroMine-v1.3.83) will crash game instantly works fine by removing EnviroMine or EnderIO

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 24/01/15 10:44
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: 3
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
	at enviromine.handlers.ObjectHandler.registerEntities(ObjectHandler.java:177)
	at enviromine.core.EnviroMine.preInit(EnviroMine.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
	at enviromine.handlers.ObjectHandler.registerEntities(ObjectHandler.java:177)
	at enviromine.core.EnviroMine.preInit(EnviroMine.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_20, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1868508376 bytes (1781 MB) / 3122659328 bytes (2978 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16384m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 93 mods loaded, 93 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1286} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1286} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized
	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
	betterstorage{0.11.3.123} [BetterStorage] (BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (buildcraft-compat-6.3.1.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.4.2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.2.1} [Chisel] (Chisel 2-2.2.1.jar) Unloaded->Constructed->Pre-initialized
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
	cookiecore{1.3.0} [Cookie Core] (cookiecore-1.3.0.jar) Unloaded->Constructed->Pre-initialized
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.6.317} [Ender IO] (EnderIO-1.7.10-2.2.6.317.jar) Unloaded->Constructed->Pre-initialized
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	enviromine{1.3.83} [EnviroMine] (EnviroMine-v1.3.83.jar) Unloaded->Constructed->Errored
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized
	rftl{1.7.10} [Rotten Flesh to Leather] (Forge SSP SMP - Rotten Flesh 1.7.2 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.7} [Galacticraft Core] (GalacticraftCore-1.7-3.0.7.252.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.7} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.7.252.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.2.157.jar) Unloaded->Constructed->Pre-initialized
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.2.157.jar) Unloaded->Constructed->Pre-initialized
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.2.157.jar) Unloaded->Constructed->Pre-initialized
	MinesweeperMod{1.4.6} [Minesweeper Mod] (Minesweeper Mod-1.4.7.jar) Unloaded->Constructed->Pre-initialized
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed->Pre-initialized
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
	neiintegration{1.0.3} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.8.59} [ProjectRed] (ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized
	OpenComputers{1.4.5.28} [OpenComputers] (OpenComputers-MC1.7.10-1.4.5.28-universal.jar) Unloaded->Constructed->Pre-initialized
	fodc{1.6.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.0.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized
	planetguyLib{1.2} [planetguyLib] (PlanetguyLib-1.2.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.5.8.59} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.5.8.59} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.8.59-World.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.5.8.59} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.8.59-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.5.8.59} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.5.8.59} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.8.59-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.5.8.59} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	JAKJ_RedstoneInMotion{2.4.0} [Remain In Motion] (RemainInMotion-2.4.0.jar) Unloaded->Constructed->Pre-initialized
	JAKJ_RedstoneInMotion_HollowCarriages{1.0} [JAKJ_RedstoneInMotion_HollowCarriages] (RemainInMotion-2.4.0.jar) Unloaded->Constructed->Pre-initialized
	ResonantEngine{3.3.0} [Resonant Engine] (resonant-engine-3.3.0.423-core.jar) Unloaded->Constructed->Pre-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.382.jar) Unloaded->Constructed->Pre-initialized
	SolarExpansion{1.4c} [Solar Expansion] (SolarExpansion-Basic-1.4c.jar) Unloaded->Constructed->Pre-initialized
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized
	StevesAddons{0.6.8} [Steve's Addons] (StevesAddons-1.7.10-0.6.8.jar) Unloaded->Constructed->Pre-initialized
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
	TSteelworks{1.7.10-1.0.7} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized
	AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7800 Series GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MatthiasMann** [comment]
This is an EnviroMine issue or it's configuration as that mod doesn't request an unique entity ID
