### ISSUE TITLE
crash i don't know is malisis doors or ender quarry

### ISSUE THREAD

**Issue by frank89722** [CrazyPants/EnderIO#1751]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/24/15 4:09 AM
Description: Exception while updating neighbours

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149720_d(Lnet/minecraft/world/IBlockAccess;III)I
	at net.malisis.doors.door.tileentity.FenceGateTileEntity.updateCamo(FenceGateTileEntity.java:102)
	at net.malisis.doors.door.block.FenceGate.func_149695_a(FenceGate.java:108)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:653)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.harvestBlock(TileEntityEnderQuarry.java:632)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:557)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.malisis.doors.door.tileentity.FenceGateTileEntity.updateCamo(FenceGateTileEntity.java:102)
	at net.malisis.doors.door.block.FenceGate.func_149695_a(FenceGate.java:108)

-- Block being updated --
Details:
	Source block type: ID #583 (tile.foliage // biomesoplenty.common.blocks.BlockBOPFoliage)
	Block type: ID #107 (tile.fenceGate // net.malisis.doors.door.block.FenceGate)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (818,69,-183), Chunk: (at 2,4,9 in 51,-12; contains blocks 816,0,-192 to 831,255,-177), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:653)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.harvestBlock(TileEntityEnderQuarry.java:632)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:557)
	at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)

-- Block entity being ticked --
Details:
	Name: enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry
	Block type: ID #1474 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (798,70,-63), Chunk: (at 14,4,1 in 49,-4; contains blocks 784,0,-64 to 799,255,-49), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #1474 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 80 Drop: 0
	Level seed: 2930071068538130878
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by MatthiasMann** [comment]
Ender Quarry is part of Extra Utilities and not EnderIO

**Comment by 6210classick** [comment]
try using Ender Markers instead of fences 

or set B:config.enableCamoFenceGate=false
in malisisdoors config file
