### ISSUE TITLE
Dark steel ladder game crash when climbing or breaking

### ISSUE THREAD

**Issue by lAimBotl** [CrazyPants/EnderIO#1810]
here is the error:

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 1/30/15 2:23 PM
Description: Colliding entity with block

java.lang.NoClassDefFoundError: codechicken/lib/math/MathHelper
	at crazypants.enderio.block.BlockDarkSteelLadder.func_149670_a(BlockDarkSteelLadder.java:53)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.math.MathHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.block.BlockDarkSteelLadder.func_149670_a(BlockDarkSteelLadder.java:53)

-- Block being collided with --
Details:
	Block type: ID #211 (tile.blockDarkSteelLadder // crazypants.enderio.block.BlockDarkSteelLadder)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-880,66,171), Chunk: (at 0,4,11 in -55,10; contains blocks -880,0,160 to -865,255,175), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)

-- Entity being checked for collision --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 348
	Entity Name: lAimBotl
	Entity's Exact location: -879.47, 66.42, 171.43
	Entity's Block location: World: (-880,66,171), Chunk: (at 0,4,11 in -55,10; contains blocks -880,0,160 to -865,255,175), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Entity's Momentum: 0.00, -0.16, 0.00
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1eeab448
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 250829872 bytes (239 MB) / 485990400 bytes (463 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.7.325} [Ender IO] (EnderIO-1.7.10-2.2.7.325.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['lAimBotl'/348, l='thermal/ender IO', x=-879.47, y=66.42, z=171.43]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client bra

**Comment by lAimBotl** [comment]
I am a noob, how would i use that?

**Comment by tterrag1098** [comment]
Wait for the next dev build to be done.

**Comment by lAimBotl** [comment]
ok
