### ISSUE TITLE
RR3 3.2.3.1. microblock? + EnderIO crash

### ISSUE THREAD

**Issue by raxixor** [CrazyPants/EnderIO#1888]
I don't exactly know what to put in the title, since it happened when I updated my resonant rise 3 server to 3.2.3.1. 
Error looks like this:

```
java.lang.NullPointerException: Exception in server tick loop
	at TEnergyReceiver$$27$class.receiveEnergy(Unknown Source)
	at TileMultipart_cmp$$44.receiveEnergy(Unknown Source)
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:291)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:264)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:221)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:32)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:542)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_213_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by MatthiasMann** [comment]
Which EnderIO version?

**Comment by raxixor** [comment]
2.2.7.331

**Comment by MatthiasMann** [comment]
That should have been fixed in build 320.
What is in that micro block - and did break it cause the crash?

**Comment by raxixor** [comment]
I just found out, that there's two EnderIO .jar files. I deleted the old one, like .27 or something, and it should be fine. I might've forgotten to delete the old mods before uploading new. :rage:
