### ISSUE TITLE
EnderIO-1.7.10-2.2.8.344 Energy Conduit Crash.

### ISSUE THREAD

**Issue by Badcholo** [CrazyPants/EnderIO#1890]
Edit>>>>>>>>>>>>>>>>>>>>>>
I have just removed all the mods and left only Ender IO and it works great.
As soon as i install these together below, it causes server and client to crash when i 
Placing a Energy conduit on anything like a thermal expansion energy cube, a mechanism cube 
or anything that interacts with it causes the server and client to crash.
I use this version of CoFHCore because the updated versions cause my server to crash upon startup.
CoFHCore-[1.7.10]3.0.0B6-32
EnderIO-1.7.10-2.2.8.344
ThermalExpansion-[1.7.10]4.0.0B6-16
ThermalFoundation-[1.7.10]1.0.0B3-8
>>>>>>>>>>>>>>>>>>>>>>>>>
I am using cauldron-1.7.10-1.1207.01.198-server
even on a forge client 1.7.10-Recommended 	10.13.2.1291
Placing a Energy conduit on anything like a thermal expansion energy cube, a mechanism cube 
or anything that interacts with it causes the server and client to crash.

Crash report
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/9/15 5:52 PM
Description: Ticking block entity

java.lang.IncompatibleClassChangeError: Class crazypants.enderio.machine.capbank.TileCapBank does not implement the requested interface cofh.api.energy.IEnergyReceiver
	at crazypants.enderio.power.EnergyReceiverPI.canConduitConnect(EnergyReceiverPI.java:22)
	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:424)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:511)
	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:359)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:534)
	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:316)
	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:702)
	at net.minecraft.world.World.func_147453_f(World.java:4556)
	at crazypants.enderio.machine.capbank.TileCapBank.func_145845_h(TileCapBank.java:210)
	at net.minecraft.world.World.func_72939_s(World.java:2487)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.power.EnergyReceiverPI.canConduitConnect(EnergyReceiverPI.java:22)
	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:424)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:511)
	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:359)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:534)
	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:316)
	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:702)
	at net.minecraft.world.World.func_147453_f(World.java:4556)
	at crazypants.enderio.machine.capbank.TileCapBank.func_145845_h(TileCapBank.java:210)

-- Block entity being ticked --
Details:
	Name: blockCapBankTileEntity // crazypants.enderio.machine.capbank.TileCapBank
	Block type: ID #568 (tile.blockCapBank // crazypants.enderio.machine.capbank.BlockCapBank)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-62,72,28), Chunk: (at 2,4,12 in -4,1; contains blocks -64,0,16 to -49,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #568 (tile.blockCapBank // crazypants.enderio.machine.capbank.BlockCapBank)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2487)
	at

**Comment by Badcholo** [comment]
I am now currently using these versions as the top mentioned versions cause incompatibilities.
These seem to be the latest working together versions. sucks for me to have to find them. 
cauldron-1.7.10-1.1207.01.198-server
EnderIO-1.7.10-2.2.2.285
CoFHCore-[1.7.10]3.0.0B6-32
ThermalExpansion-[1.7.10]4.0.0B6-16
ThermalFoundation-[1.7.10]1.0.0B3-8

**Comment by tterrag1098** [comment]
Um..that EnderIO is very outdated, you should use a newer version.

**Comment by tterrag1098** [comment]
This crash is caused by an old RF API in another mod, that combination only works because you downgraded EIO

**Comment by Badcholo** [comment]
Yeah, CoFH core doesn't seem to work past this version. I wish there was a timeline or sync style for compatibility between mods. It seems like a major mod makes a huge update and doesn't care about how others will interact with it.
