### ISSUE TITLE
Crash using Ender IO and Minefactory Reloaded (latest version)

### ISSUE THREAD

**Issue by Dan9999** [CrazyPants/EnderIO#1989]
The crash report is as follows:
---- Minecraft Crash Report ----
// My bad.

Time: 2/22/15 7:31 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lcrazypants/enderio/conduit/BlockConduitBundle;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduit.BlockConduitBundle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: powercrystals/minefactoryreloaded/api/rednet/IRedNetOmniNode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: powercrystals.minefactoryreloaded.api.rednet.IRedNetOmniNode
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 335901248 bytes (320 MB) / 602931200 bytes (575 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:PermSize=256m -XX:MaxPermSize=512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 87 mods loaded, 87 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0RC1} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC1-181.jar) Unloaded->Errored
	ThermalFoundation{1.7.10R1.0.0RC2} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC2-53.jar) Unloaded->Errored
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Errored
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Errored
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	chisel{2.3.7.34} [Chisel 2] (Chisel2-2.3.7.34.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Errored
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded
	FastCraft{1.12} [FastCraft] (fastcraft-1.12.jar) Unloaded
	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5a.jar) Unloaded
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil-4.1.2.jar) Unloaded
	IC2{2.2.675-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.675-experimental.jar) Unloaded
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded
	journeymap{5.0.0} [JourneyMap] (JourneyMap5.0.0_Unlimited_MC1.7.10.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded
	ProjRed|Core{4.5.10.61} [ProjectRed] (ProjectRed-1.7.10-4.5.10.61-Base.jar) Unloaded
	ProjRed|Exploration{4.5.10.61} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.10.61-World.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-15.jar) Unloaded
	Morph{0.9.0} [Morph] (Morph-Beta-0.9.0.jar) Unloaded
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded
	ProjRed|Transmission{4.5.10.61} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.10.61-Integration.jar) Unloaded
	ProjRed|Transportation{4.5.10.61} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.10.61-Mechanical_beta.jar) Unloaded
	ProjRed|Compatibility{4.5.10.61} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.10.61-Compat.jar) Unloaded
	ProjRed|Integration{4.5.10.61} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.10.61-Integration.jar) Unloaded
	ProjRed|Illumination{4.5.10.61} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.10.61-Lighting.jar) Unloaded
	ProjRed|Expansion{4.5.10.61} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.10.61-Mechanical_beta.jar) Unloaded
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	aobd{2.3.6} [Another One Bites The Dust] (AOBD-2.3.6.jar) Unloaded
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	CoFHCore: -[1.7.10]3.0.0RC1-181
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: ATI Mobility Radeon HD 4200 Series GL version 3.3.10242 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.6.4.zip, JSTR_Universal_1.7.x.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by RikuSS4** [comment]
I had this issue too. Had to update forge to version 1291.

**Comment by tterrag1098** [comment]
#1981
