### ISSUE TITLE
crash on loading using new thermal expanion updates RC2/RC3

### ISSUE THREAD

**Issue by evilives34** [CrazyPants/EnderIO#1997]
endo---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/23/15 3:30 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lcrazypants/enderio/conduit/BlockConduitBundle;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduit.BlockConduitBundle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: powercrystals/minefactoryreloaded/api/rednet/IRedNetOmniNode
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: powercrystals.minefactoryreloaded.api.rednet.IRedNetOmniNode
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredField(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 102884088 bytes (98 MB) / 309878784 bytes (295 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_B5 104 mods loaded, 104 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed
	AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed
	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0RC2} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC2-195.jar) Unloaded->Errored
	BuildCraft|Core{6.3.6} [BuildCraft] (buildcraft-6.3.6.jar) Unloaded->Constructed
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0RC7} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded->Errored
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.8.352} [Ender IO] (EnderIO-1.7.10-2.2.8.352.jar) Unloaded
	ThermalFoundation{1.7.10R1.0.0RC3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC3-56.jar) Unloaded
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded
	ThermalExpansion{1.7.10R4.0.0RC2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC2-129.jar) Unloaded
	RedstoneArsenal{1.7.10R1.1.0RC2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC2-43.jar) Unloaded
	BuildCraft|Energy{6.3.6} [BC Energy] (buildcraft-6.3.6.jar) Unloaded
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded
	Mekanism{7.1.2} [Mekanism] (Mekanism-1.7.10-7.1.2.177.jar) Unloaded
	appliedenergistics2{rv0-stable-10} [Applied Energistics 2] (appliedenergistics2-rv0-stable-10.jar) Unloaded
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded
	BBG{1.0.0} [BetterBedrockGen] (BBG-1.0.0.jar) Unloaded
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded
	BuildCraft|Transport{6.3.6} [BC Transport] (buildcraft-6.3.6.jar) Unloaded
	BuildCraft|Silicon{6.3.6} [BC Silicon] (buildcraft-6.3.6.jar) Unloaded
	BuildCraft|Builders{6.3.6} [BC Builders] (buildcraft-6.3.6.jar) Unloaded
	BuildCraft|Factory{6.3.6} [BC Factory] (buildcraft-6.3.6.jar) Unloaded
	CarpentersBlocks{3.3.4.4} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.4 - MC 1.7.10.jar) Unloaded
	chisel{2.3.5.31} [Chisel 2] (Chisel2-2.3.5.31.jar) Unloaded
	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) Unloaded
	DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded
	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded
	SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) Unloaded
	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) Unloaded
	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) Unloaded
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded
	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar) Unloaded
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded
	MekanismGenerators{7.1.2} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.2.177.jar) Unloaded
	MekanismTools{7.1.2} [MekanismTools] (MekanismTools-1.7.10-7.1.2.177.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC7} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC7} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC7} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC7} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC7} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC7} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC7} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC7} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC7} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC7} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded
	ProjRed|Core{4.5.10.61} [ProjectRed] (ProjectRed-1.7.10-4.5.10.61-Base.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC7} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC7} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC7} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC7} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC7} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC7} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC7} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC7} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC7} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar) Unloaded
	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded
	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.176.jar) Unloaded
	MorePistons{2.0.0 Beta 1.0} [More Pistons] (More_Pistons-1.7.10-2.0.0Beta1.0.jar) Unloaded
	openmodularturrets{1.3.3} [Open Modular Turrets] (OpenModularTurrets-1.7.10-1.3.3-25.jar) Unloaded
	powersuitaddons{@VERSION@} [Modular Powersuits Addon] (powersuitaddons-1.7.10-901.jar) Unloaded
	ProjRed|Integration{4.5.10.61} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.10.61-Integration.jar) Unloaded
	ProjRed|Transmission{4.5.10.61} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.10.61-Integration.jar) Unloaded
	ProjRed|Illumination{4.5.10.61} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.10.61-Lighting.jar) Unloaded
	rftools{2.21} [RFTools] (rftools-2.21.jar) Unloaded
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded
	SGCraft{1.9.0} [Greg's SG Craft] (SGCraft-1.9.0-mc1.7.10.jar) Unloaded
	simplyjetpacks{1.3.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded
	SolarFlux{1.7.10-0.5a} [Solar Flux] (SolarFlux-1.7.10-0.5a.jar) Unloaded
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded
	Torched{4.0.0} [Torched] (Torched-4.0.0.jar) Unloaded
	torchLevers{1.4.1} [Torch Levers] (TorchLeversV1.4.1.jar) Unloaded
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	CoFHCore: -[1.7.10]3.0.0RC2-195
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Sphax PureBDcraft  32x MC17.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by Error998** [comment]
Update to forge to 1291

**Comment by kenny608uk** [comment]
So essentially those of us who are using cauldron are SOL on wanting to use Thermal Dynamics + EnderIO together I guess?

**Comment by evilives34** [comment]
please close some how forge profile was using a older version and i didnt notice, changing back to 1291 forge fixed it

**Comment by tterrag1098** [comment]
@kenny608uk 1291 is only required on the client.
