### ISSUE TITLE
Bugged Conduit Connectors after Server Crash; cant destroy them

### ISSUE THREAD

**Issue by DatJonas01** [CrazyPants/EnderIO#2026]
Im playing on FTB Direwolf20 1.0.3 and my Server crashed for whatever reason.
After restarting it, the conduits of my mining machine were bugged:

They have been replaced by "Conduit Connectors" as you can see here;

![2015-02-28_22 15 56](https://cloud.githubusercontent.com/assets/11249620/6428219/f6b2b4a8-bf99-11e4-92b1-67598d1ec29c.png)

Everytime I try to break or right click them, I get kicked by the Server: "Internal Server Error".

The Server Log says the following:

[22:29:13] [Server thread/WARN]: Failed to handle packet for /11.11.11.11:54791
java.lang.ClassCastException: buildcraft.factory.TileMiningWell cannot be cast to crazypants.enderio.conduit.IConduitBundle
	at crazypants.enderio.conduit.BlockConduitBundle.func_149727_a(BlockConduitBundle.java:470) ~[BlockConduitBundle.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[22:29:13] [Server thread/INFO]: BrainSlug lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[22:29:13] [Server thread/INFO]: BrainSlug left the game

**Comment by MatthiasMann** [comment]
That sounds like your block ID table got corrupted - do you have a backup of your world?

**Comment by DatJonas01** [comment]
Wouldn't that change other conduits in the world, too?
I think this bug occured because the miningmachine was moving at the time of the crash/restart...

I just want to remove these blocks without restoring a relativly old backup

**Comment by tterrag1098** [comment]
Go into MCEdit and remove them then. This not an EIO bug, just seems like world corruption.
